# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa9ca361b304845c7050caea7a1f18a15c9e5d7b388b4ab260c941e99debcc04f578fe7f52c0060a3515ba2274d1d12ffd71e78418d7b93a360cfb2fbdf9739

test:
  secret_key_base: 06ad5e59a30a016985a54a236e7d98fc7bc040dc88db08e1c15e12fb3dac74a4371916b979fb541b0b9b09214f4818a84a2398c1f937bc67890a1f4badf160f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
